### PR TITLE
Move to using tap cmd directory.

### PR DESCRIPTION
**Pull request by jsfaint**
With this modification brew-rmtree can be used without `brew install`
`brew tap beeftornado/rmtree` is enough :)

Just like brew-cask changed in https://github.com/caskroom/homebrew-cask/pull/15381
- brew-rmtree.rb
  Move brew-rmtree.rb to cmd/brew-rmtree.rb.
- Formula/brew-rmtree.rb
  Remove Formula, because we don't need it anymore.
- README.md
  Modify the installation section.

### CODE REVIEW

**Comment by beeftornado** [comment]
I'm not sure I completely understand how this works yet, but the concept sounds great. Let me test it out locally to get a feel for it and I'll get back to you. Thanks for the link to cask's PR

**Comment by jsfaint** [comment]
+beeftornado you can refer the external command part of this article
https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-to-Create-and-Maintain-a-Tap.md

**Comment by bfontaine** [comment]
I came here to write the same PR :smile: 

@beeftornado In addition to the `PATH`, Homebrew checks the `cmd` directory of each tap to find commands. So any executable named `brew-something` (or `brew-something.rb` if it’s in Ruby) under `cmd/` will be available as a command.

**Comment by tsparber** [comment]
`brew doctor` is now [issuing a warning](https://github.com/Homebrew/brew/pull/1676) for the `brew-rmtree.rb` file in the taps root.

```
Warning: Found Ruby file outside beeftornado/rmtree tap formula directory
(/usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/Formula):
  /usr/local/Homebrew/Library/Taps/beeftornado/homebrew-rmtree/brew-rmtree.rb
```

Using this PR fixes the warning too. Thank you for the script!

**Comment by sepehr** [comment]
Doctor's warning is getting annoying. That'd be great if you consider merging this. @beeftornado

**Pull request merged**
